/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atomic Number</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mdsd.rPG.RPGPackage#getAtomicNumber()
 * @model
 * @generated
 */
public interface AtomicNumber extends Multiply
{
} // AtomicNumber
