/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute Values</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdsd.rPG.AttributeValues#getLTypes <em>LTypes</em>}</li>
 *   <li>{@link mdsd.rPG.AttributeValues#getAn <em>An</em>}</li>
 * </ul>
 *
 * @see mdsd.rPG.RPGPackage#getAttributeValues()
 * @model
 * @generated
 */
public interface AttributeValues extends EObject
{
  /**
   * Returns the value of the '<em><b>LTypes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>LTypes</em>' attribute.
   * @see #setLTypes(String)
   * @see mdsd.rPG.RPGPackage#getAttributeValues_LTypes()
   * @model
   * @generated
   */
  String getLTypes();

  /**
   * Sets the value of the '{@link mdsd.rPG.AttributeValues#getLTypes <em>LTypes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>LTypes</em>' attribute.
   * @see #getLTypes()
   * @generated
   */
  void setLTypes(String value);

  /**
   * Returns the value of the '<em><b>An</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>An</em>' containment reference.
   * @see #setAn(ActualNumbers)
   * @see mdsd.rPG.RPGPackage#getAttributeValues_An()
   * @model containment="true"
   * @generated
   */
  ActualNumbers getAn();

  /**
   * Sets the value of the '{@link mdsd.rPG.AttributeValues#getAn <em>An</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>An</em>' containment reference.
   * @see #getAn()
   * @generated
   */
  void setAn(ActualNumbers value);

} // AttributeValues
