/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bigger Eq</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mdsd.rPG.RPGPackage#getBiggerEq()
 * @model
 * @generated
 */
public interface BiggerEq extends Comparator
{
} // BiggerEq
