/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comparator</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mdsd.rPG.RPGPackage#getComparator()
 * @model
 * @generated
 */
public interface Comparator extends EObject
{
} // Comparator
