/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Moves</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdsd.rPG.EntityMoves#getMove <em>Move</em>}</li>
 * </ul>
 *
 * @see mdsd.rPG.RPGPackage#getEntityMoves()
 * @model
 * @generated
 */
public interface EntityMoves extends EObject
{
  /**
   * Returns the value of the '<em><b>Move</b></em>' reference list.
   * The list contents are of type {@link mdsd.rPG.Move}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Move</em>' reference list.
   * @see mdsd.rPG.RPGPackage#getEntityMoves_Move()
   * @model
   * @generated
   */
  EList<Move> getMove();

} // EntityMoves
