/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Float Num</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdsd.rPG.FloatNum#getI <em>I</em>}</li>
 *   <li>{@link mdsd.rPG.FloatNum#getDecimal <em>Decimal</em>}</li>
 * </ul>
 *
 * @see mdsd.rPG.RPGPackage#getFloatNum()
 * @model
 * @generated
 */
public interface FloatNum extends ActualNumbers
{
  /**
   * Returns the value of the '<em><b>I</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>I</em>' attribute.
   * @see #setI(int)
   * @see mdsd.rPG.RPGPackage#getFloatNum_I()
   * @model
   * @generated
   */
  int getI();

  /**
   * Sets the value of the '{@link mdsd.rPG.FloatNum#getI <em>I</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>I</em>' attribute.
   * @see #getI()
   * @generated
   */
  void setI(int value);

  /**
   * Returns the value of the '<em><b>Decimal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decimal</em>' attribute.
   * @see #setDecimal(int)
   * @see mdsd.rPG.RPGPackage#getFloatNum_Decimal()
   * @model
   * @generated
   */
  int getDecimal();

  /**
   * Sets the value of the '{@link mdsd.rPG.FloatNum#getDecimal <em>Decimal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decimal</em>' attribute.
   * @see #getDecimal()
   * @generated
   */
  void setDecimal(int value);

} // FloatNum
