/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Members</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdsd.rPG.Members#getEntity <em>Entity</em>}</li>
 * </ul>
 *
 * @see mdsd.rPG.RPGPackage#getMembers()
 * @model
 * @generated
 */
public interface Members extends EObject
{
  /**
   * Returns the value of the '<em><b>Entity</b></em>' reference list.
   * The list contents are of type {@link mdsd.rPG.Entity}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' reference list.
   * @see mdsd.rPG.RPGPackage#getMembers_Entity()
   * @model
   * @generated
   */
  EList<Entity> getEntity();

} // Members
