/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Move E</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdsd.rPG.MoveE#getExtraRule <em>Extra Rule</em>}</li>
 * </ul>
 *
 * @see mdsd.rPG.RPGPackage#getMoveE()
 * @model
 * @generated
 */
public interface MoveE extends Effect
{
  /**
   * Returns the value of the '<em><b>Extra Rule</b></em>' containment reference list.
   * The list contents are of type {@link mdsd.rPG.Rule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extra Rule</em>' containment reference list.
   * @see mdsd.rPG.RPGPackage#getMoveE_ExtraRule()
   * @model containment="true"
   * @generated
   */
  EList<Rule> getExtraRule();

} // MoveE
