/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relations</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdsd.rPG.Relations#getType <em>Type</em>}</li>
 *   <li>{@link mdsd.rPG.Relations#getSyn <em>Syn</em>}</li>
 *   <li>{@link mdsd.rPG.Relations#getEff <em>Eff</em>}</li>
 *   <li>{@link mdsd.rPG.Relations#getIneff <em>Ineff</em>}</li>
 * </ul>
 *
 * @see mdsd.rPG.RPGPackage#getRelations()
 * @model
 * @generated
 */
public interface Relations extends Declaration
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference list.
   * The list contents are of type {@link mdsd.rPG.Type}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference list.
   * @see mdsd.rPG.RPGPackage#getRelations_Type()
   * @model containment="true"
   * @generated
   */
  EList<Type> getType();

  /**
   * Returns the value of the '<em><b>Syn</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Syn</em>' containment reference.
   * @see #setSyn(ActualNumbers)
   * @see mdsd.rPG.RPGPackage#getRelations_Syn()
   * @model containment="true"
   * @generated
   */
  ActualNumbers getSyn();

  /**
   * Sets the value of the '{@link mdsd.rPG.Relations#getSyn <em>Syn</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Syn</em>' containment reference.
   * @see #getSyn()
   * @generated
   */
  void setSyn(ActualNumbers value);

  /**
   * Returns the value of the '<em><b>Eff</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eff</em>' containment reference.
   * @see #setEff(ActualNumbers)
   * @see mdsd.rPG.RPGPackage#getRelations_Eff()
   * @model containment="true"
   * @generated
   */
  ActualNumbers getEff();

  /**
   * Sets the value of the '{@link mdsd.rPG.Relations#getEff <em>Eff</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Eff</em>' containment reference.
   * @see #getEff()
   * @generated
   */
  void setEff(ActualNumbers value);

  /**
   * Returns the value of the '<em><b>Ineff</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ineff</em>' containment reference.
   * @see #setIneff(ActualNumbers)
   * @see mdsd.rPG.RPGPackage#getRelations_Ineff()
   * @model containment="true"
   * @generated
   */
  ActualNumbers getIneff();

  /**
   * Sets the value of the '{@link mdsd.rPG.Relations#getIneff <em>Ineff</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ineff</em>' containment reference.
   * @see #getIneff()
   * @generated
   */
  void setIneff(ActualNumbers value);

} // Relations
