/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Smaller</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mdsd.rPG.RPGPackage#getSmaller()
 * @model
 * @generated
 */
public interface Smaller extends Comparator
{
} // Smaller
