/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System RPG</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdsd.rPG.SystemRPG#getName <em>Name</em>}</li>
 *   <li>{@link mdsd.rPG.SystemRPG#getDeclarations <em>Declarations</em>}</li>
 * </ul>
 *
 * @see mdsd.rPG.RPGPackage#getSystemRPG()
 * @model
 * @generated
 */
public interface SystemRPG extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see mdsd.rPG.RPGPackage#getSystemRPG_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link mdsd.rPG.SystemRPG#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Declarations</b></em>' containment reference list.
   * The list contents are of type {@link mdsd.rPG.Declaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declarations</em>' containment reference list.
   * @see mdsd.rPG.RPGPackage#getSystemRPG_Declarations()
   * @model containment="true"
   * @generated
   */
  EList<Declaration> getDeclarations();

} // SystemRPG
