/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdsd.rPG.TypeExpression#getStrong <em>Strong</em>}</li>
 *   <li>{@link mdsd.rPG.TypeExpression#getStrong2 <em>Strong2</em>}</li>
 *   <li>{@link mdsd.rPG.TypeExpression#getCurrentT <em>Current T</em>}</li>
 *   <li>{@link mdsd.rPG.TypeExpression#getWeak <em>Weak</em>}</li>
 *   <li>{@link mdsd.rPG.TypeExpression#getWeak2 <em>Weak2</em>}</li>
 * </ul>
 *
 * @see mdsd.rPG.RPGPackage#getTypeExpression()
 * @model
 * @generated
 */
public interface TypeExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Strong</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Strong</em>' reference.
   * @see #setStrong(Type)
   * @see mdsd.rPG.RPGPackage#getTypeExpression_Strong()
   * @model
   * @generated
   */
  Type getStrong();

  /**
   * Sets the value of the '{@link mdsd.rPG.TypeExpression#getStrong <em>Strong</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Strong</em>' reference.
   * @see #getStrong()
   * @generated
   */
  void setStrong(Type value);

  /**
   * Returns the value of the '<em><b>Strong2</b></em>' reference list.
   * The list contents are of type {@link mdsd.rPG.Type}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Strong2</em>' reference list.
   * @see mdsd.rPG.RPGPackage#getTypeExpression_Strong2()
   * @model
   * @generated
   */
  EList<Type> getStrong2();

  /**
   * Returns the value of the '<em><b>Current T</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Current T</em>' reference.
   * @see #setCurrentT(Type)
   * @see mdsd.rPG.RPGPackage#getTypeExpression_CurrentT()
   * @model
   * @generated
   */
  Type getCurrentT();

  /**
   * Sets the value of the '{@link mdsd.rPG.TypeExpression#getCurrentT <em>Current T</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Current T</em>' reference.
   * @see #getCurrentT()
   * @generated
   */
  void setCurrentT(Type value);

  /**
   * Returns the value of the '<em><b>Weak</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Weak</em>' reference.
   * @see #setWeak(Type)
   * @see mdsd.rPG.RPGPackage#getTypeExpression_Weak()
   * @model
   * @generated
   */
  Type getWeak();

  /**
   * Sets the value of the '{@link mdsd.rPG.TypeExpression#getWeak <em>Weak</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Weak</em>' reference.
   * @see #getWeak()
   * @generated
   */
  void setWeak(Type value);

  /**
   * Returns the value of the '<em><b>Weak2</b></em>' reference list.
   * The list contents are of type {@link mdsd.rPG.Type}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Weak2</em>' reference list.
   * @see mdsd.rPG.RPGPackage#getTypeExpression_Weak2()
   * @model
   * @generated
   */
  EList<Type> getWeak2();

} // TypeExpression
