/*
 * generated by Xtext 2.21.0
 */
package mdsd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RPGUiModule extends AbstractRPGUiModule {

	public RPGUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
