/*
 * generated by Xtext 2.21.0
 */
package mdsd.ui;

import com.google.inject.Injector;
import mdsd.rpg.ui.internal.RpgActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RPGExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(RpgActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		RpgActivator activator = RpgActivator.getInstance();
		return activator != null ? activator.getInjector(RpgActivator.MDSD_RPG) : null;
	}

}
