/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG.impl;

import mdsd.rPG.BiggerEq;
import mdsd.rPG.RPGPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Bigger Eq</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BiggerEqImpl extends ComparatorImpl implements BiggerEq
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BiggerEqImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RPGPackage.Literals.BIGGER_EQ;
  }

} //BiggerEqImpl
