/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG.impl;

import mdsd.rPG.RPGPackage;
import mdsd.rPG.SmallerEq;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Smaller Eq</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SmallerEqImpl extends ComparatorImpl implements SmallerEq
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SmallerEqImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RPGPackage.Literals.SMALLER_EQ;
  }

} //SmallerEqImpl
