/*
 * generated by Xtext 2.21.0
 */
package mdsd.ui.quickfix;

import org.eclipse.xtext.ui.editor.model.IXtextDocument;
import org.eclipse.xtext.ui.editor.model.edit.IModification;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;

import mdsd.validation.RPGValidator;

/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
public class RPGQuickfixProvider extends DefaultQuickfixProvider {

    @Fix(RPGValidator.INVALID_NAME)
    public void capitalizeName(final Issue issue, IssueResolutionAcceptor acceptor) {
        acceptor.accept(issue, "Capitalize name", "Capitalize the name.", "upcase.png", new IModification() {
            @Override
            public void apply(IModificationContext context) throws Exception {
                IXtextDocument xtextDocument = context.getXtextDocument();
                String firstLetter = xtextDocument.get(issue.getOffset(), 1);
                xtextDocument.replace(issue.getOffset(), 1, firstLetter.toUpperCase());
            }
        });
    }

}

