/*
 * generated by Xtext 2.21.0
 */
package mdsd.parser.antlr;

import com.google.inject.Inject;
import mdsd.parser.antlr.internal.InternalRPGParser;
import mdsd.services.RPGGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class RPGParser extends AbstractAntlrParser {

	@Inject
	private RPGGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRPGParser createParser(XtextTokenStream stream) {
		return new InternalRPGParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SystemRPG";
	}

	public RPGGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RPGGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
