/*
 * generated by Xtext 2.21.0
 */
package mdsd;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RPGStandaloneSetup extends RPGStandaloneSetupGenerated {

	public static void doSetup() {
		new RPGStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
